services:
  app:
    container_name: vintage_story_dedicated_server
    image: vintage_story_dedicated_server:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    #tty: true
    #stdin_open: true
    ports:
      - 42420:42420/tcp
      - 42420:42420/udp
    volumes:
      - ./data:/data